### ISSUE TITLE
Specification not easy to discover on openapis.org

### ISSUE THREAD

**Issue by martin-kokos** [OAI/OpenAPI-Style-Guide#17] opened 2019-05-02 08:35 UTC
When I search for "openapi specification" I will get https://www.openapis.org/ as first result, I go to the website and there is no obvious link to the specification. There is a _Specification_ button, but it's only a menu. I am expecting a direct link to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md or better yet a smarter presentation than an md file such as https://swagger.io/specification/

**Comment by MikeRalphson** [comment] 2019-05-02 09:12
Duplicate of https://github.com/OAI/OpenAPI-Specification/issues/1641

**Closed** 2021-12-11 13:29 UTC
